Openl10n\Domain\User\Application\Action\RegisterUserAction:
    properties:
        username:
            - Openl10n\Bundle\UserBundle\Validator\Constraints\UniqueUser: ~
            - NotBlank: ~
            - Regex: "/^[a-zA-Z0-9\-\.\_]+$/"
        displayName:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
        password:
            - NotBlank: ~
            - Length:
                min: 6

Openl10n\Domain\User\Application\Action\EditProfileAction:
    properties:
        displayName:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~

Openl10n\Domain\User\Application\Action\ChangePasswordAction:
    properties:
        oldPassword:
            - NotBlank: ~
            - Symfony\Component\Security\Core\Validator\Constraints\UserPassword: ~
        newPassword:
            - NotBlank: ~
            - Length:
                min: 6
