namespaces:
    Openl10nUser: Openl10n\Bundle\UserBundle\Validator\Constraints\

Openl10n\Bundle\UserBundle\Action\CreateUserAction:
    properties:
        username:
            - NotBlank: ~
            - Regex: "/^[a-zA-Z0-9\-\.\_]+$/"
        displayName:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
        password:
            - NotBlank: ~
            - Length:
                min: 6

Openl10n\Bundle\UserBundle\Security\User\RegisterUser:
    constraints:
        - Openl10nUser:UniqueEmail: ~
