openl10n_editor_translate:
    path:  /editor/translate/{project}
    defaults: { _controller: Openl10nEditorBundle:Editor:translate }

_openl10n_editor_api:
    type: rest
    resource: "@Openl10nEditorBundle/Resources/config/routing/api.yml"
    prefix: /editor/api
    options:
        expose: true
